### ISSUE TITLE
Some issues when trying to merge two lines

### ISSUE THREAD

**Issue by laurent22** [Krassmus/Textmerger#1]
The library seems to have troubles with some cases.

This:

```
$source = "This is the first line.\nThis is the second line.";
$target1 = "This is the first line XXX.\nThis is the second line.";
$target2 = "This is the first line.\nThis is the second line YYY.";

$r = Textmerger::get()->merge($source, $target1, $target2);
var_dump($r)
```

would output:

```
This is the first line XXX.
This is the second line.
This is the second line YYY.
```

While this:

```
$source = "This is the first line.\nThis is the second line.";
$target1 = "This is the first line.\nThis is the second line.";
$target2 = "This is the first line.\nThis is the second line.";

$r = Textmerger::get()->merge($source, $target1, $target2);
var_dump($r)
```

Would throw an exception:

```
Exception: Notice: Uninitialized string offset: 0 at Textmerger.php:560
```

**Comment by Krassmus** [comment]
Interesting! Thanx for the report. I will have a look.

**Comment by jbuddha** [comment]
I have the issue as well. 

## Original

> Twinkle Twinle Little Star
> How I what you are
> Up the world so high
> Like a diamond in the sky

## Theirs

> Twinkle Twinle Little Star
> How I **_wonder_** what you are
> Up the world so high
> Like a diamond in the sky

## Mine

> Twinkle Twinle Little Star
> How I what you are
> Up **_above_** the world so high
> Like a diamond in the sky

## Output

> Twinkle Twinle Little Star
> How I what yoonder what you are
> Upu are
> Up above the world so high
> Like a diamond in the sky

**Comment by Krassmus** [comment]
I guess, this issue is solved now. I added a test for jbuddhas example. Thanx all!
